import { Link } from 'react-router-dom';
import { scrollToTop } from '../Utils.jsx';
import { useEffect } from 'react';
import { useLenis } from 'lenis/react';

const Extended = () => {

  // always begin page from top on load
  const lenis = useLenis();

  useEffect(() => {
    scrollToTop(lenis);
  }, [lenis]);

  return (
    <main className="flex justify-center items-center font-centschbook">
      <div className="w-[70vw] xl:w-[50vw] py-12 md:py-24 xl:py-32
        text-4xs sm:text-3xs md:text-sm 3xl:text-lg 5xl:text-2xl 6xl:text-3xl">
        <h1 className="text-customOrange text-3xs sm:text-2xs md:text-base 3xl:text-xl 5xl:text-3xl 6xl:text-4xl">Extended</h1>
        <br/>
        <p>The objects I make tap the familiar. They are constructed primarily of found materials or objects that are
          reworked and combined through a variety of transformative activities. They sometimes have associations that are
          transparent – a stool, a weight, wheels – that point directly to stasis, stability or mobility. Other
          associations are ephemeral and imbedded; these are often nearly consumed in the process of making but maintain
          viability through vestiges of their former function.</p>
        <br/>
        <p>In striving to recognize an object, which seemingly has all the visual qualities of a real world object,
          viewers are forced to call up associative memories – to peruse mental inventories of the experiences that
          constitute their histories.</p>
        <br/>
        <p>My art is both the transformed material evidence of my past and a surrogate for the missing. I draw upon
          images, objects, and memories to form reliquaries of unconscious connections. I pursue concepts generated by
          previously completed (or aspects of uncompleted) work. My intention is for my art to index both the moment of
          the found materials’ past and the moment in which we experience their new context. It is the labor, integrity of
          craft, and the importance of process, that ties past and present together, and it is that which prompts
          production.</p>
        <br/>
        <p>From my childhood’s back yard I could see a culm bank that towered twice as high as any natural mountain in the
          vicinity; it was the byproduct of mining — the materials extracted along with the coal. The work that produced
          the town, undermined it, hollowing out its foundation. But waste is a proof of productivity and oddly enough,
          the ever-growing accumulation was a source of local pride. Culm banks and vacated factories are the places of my
          youth whose explorations are unequivocally linked to my art production.</p>
        <br/>
        <p>The romantic ideals, unadorned tastes, and simplified views of my hometown, Shamokin, Pennsylvania, continue to
          contribute significantly to the character of my studio production. Recent decades have seen the slow and
          encompassing collapse of the industries that prospered in Shamokin at the start of the 20th century. The utopian
          ideals that built the city are evident now only in abandoned buildings and vacant lots factories used to occupy.
          Today, Shamokin’s history is blanketed by an ancestral memory and an oral tradition that safeguards and
          maintains a pretense of a utopian past. Augmented by the exaggeration and distortion that accompanies memory,
          the routine reiterations of the ‘fact’ that “those” days were better than “these” resulted in an ingrained
          longing for the past and an unwilling acceptance of the inevitable present. This fosters a disconcerting
          susceptibility to nostalgia and I find myself coveting that which is decayed.</p>
        <br/>
        <p>‘Working’ means making better the given present; re-employing what has been gained in the pursuit of gaining
          more. The pursuit is endless and tiresome and so the objects of our everyday transform within our ongoing
          negotiation between labor and leisure. We want our rest to be productive and our productivity to be restful. We
          ‘work for the weekend’ and then strive to get work accomplished in our ‘spare time.’ We summon these extensions
          of ourselves with expectations that they will spare us from drudgery or supplement our repose. The production of
          my art – the process – is a metaphor for the use of the tools that plot and advance my day-to-day; it also
          results in objects not unlike those tools in many ways.</p>
        <br/>
        <p>My own division between labor and leisure is difficult to define. A portion of that difficulty forms the
          challenge I enjoy in making things; another part pains me. There are objects in my home that are very similar to
          my studio where there are shelves of objects I have collected and objects I have made. They are not unlike
          objects in my childhood home that I only vaguely remember and childhood discoveries of clearly functional yet
          ambiguous spaces and objects that have, over time, intensified my predilection for objects and materials still
          in possession of internal histories. Now these objects are imbued with the uncertainties of their more recent
          past. These works and their parts, these objects and their ghosts, all attest to my desires, taste, and status.
          They are indicators of the personal and the cultural. These objects and works attempt to blur the already gray
          indistinction between art exhibition, commercial display and domestic organization. Their character is adopted
          from marketable design and their purpose is borrowed from ‘art.’ Because many of these objects are neither
          traditional sculpture nor functional appliances – because many of these works impel tenuous associations with
          the familiar – they situate comfortably in a place best accessed through memory.</p>
        <br/>
        <Link to="/about" className="text-customOrange float-right">← Back</Link>
      </div>
    </main>
  );

}

export default Extended;