backend:
  name: github
  repo: jooeon/atopol
  branch: master

media_folder: "public/images"
public_folder: "/images"

collections:
  - label: "Tangents"
    name: "tangents"
    description: "\"Tangents Page Data\" is for configuring the \"allentopolski.com/tangents\" page that links to artwork groups (Something Like 2D, Almost Functional, etc). Set thumbnails and labels there.
      Do not touch the \"category\" field as it determines the URL."
    files:
      - label: "Tangents Page Data"
        name: "tangents-page-data"
        file: "src/data/tangents.json"
        fields:
          - label: "Artwork Group"
            name: "artwork-group"
            widget: "list"
            fields:
            - label: "Image"
              name: "image"
              widget: "image"
              required: true
              description: "Upload a thumbnail image for this artwork group."
            - label: "Title"
              name: "title"
              widget: "string"
              required: true
              description: "Enter the title of the artwork group (Something Like 2D, Almost Functional, etc)."
            - label: "Category"
              name: "category"
              widget: "string"
              required: true
              description: "Specify the category (e.g. something-like-2D, almost-functional). This will be used as the URL, so replace spaces with dashes (-) and avoid special characters."
  - name: "tangents-groups"
    label: "Tangents Artwork Groups"
    folder: "src/data/tangents-groups"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }

      - label: "Image Group"
        name: "imageGroup"
        widget: "list"
        fields:
          - { label: "Align", name: "align", widget: "select", options: [ "left", "center", "right" ], default: "left" }
          - { label: "Title", name: "imageGroupTitle", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
  - name: "smallScale"
    label: "Small Scale Installations"
    folder: "src/data/small-scale"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
          required: false
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "small-scale"
      }
  - name: "site-specific"
    label: "Site-Specific Installations"
    folder: "src/data/site-specific"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
          required: false
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "site-specific"
      }
  - name: "appliances"
    label: "Appliances (Objects)"
    folder: "src/data/appliances"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
          required: false
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "appliances"
      }
  - name: "coping-mechanisms"
    label: "Coping Mechanisms (Objects)"
    folder: "src/data/coping-mechanisms"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
          required: false
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "coping mechanisms"
      }