backend:
  name: github
  repo: jooeon/atopol
  branch: master

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "appliances"
    label: "Appliances"
    folder: "src/data/appliances"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
            label: "Image"
            name: "image"
            widget: "image"
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "appliances"
      }
  - name: "smallScale"
    label: "Small Scale"
    folder: "src/data/small-scale"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "small-scale"
      }
  - name: "site-specific"
    label: "Site-Specific"
    folder: "src/data/site-specific"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "site-specific"
      }