backend:
  name: github
  repo: jooeon/atopol
  branch: master

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "landingPageGalleryImage"
    label: "Landing Page Gallery Image"
    description: "Add each artwork to show on the landing page."
    folder: "src/data/landing-page"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Year", name: "year", widget: "string", required: false }
  - name: "tangents"
    label: "Tangents"
    description: "Add artwork groups (e.g. Something Like 2D, Not Unrelated to Dance) in the \"Tangents\" category."
    folder: "src/data/tangents"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        required: true
        description: "Upload a thumbnail image for this artwork group."
      - { label: "Description", name: "description", widget: "string", required: false }
      - label: "Category"
        name: "category"
        widget: "string"
        required: true
        description: "Specify the category (e.g. something-like-2D, almost-functional). This will be used as the URL, so replace spaces with dashes (-) and avoid special characters."
      - label: "Image Group"
        name: "imageGroup"
        widget: "list"
        fields:
          - { label: "Align", name: "align", widget: "select", options: [ "left", "center", "right" ], default: "left" }
          - { label: "Title", name: "imageGroupTitle", widget: "string", required: false  }
          - { label: "Description", name: "description", widget: "text", required: false  }
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
  - name: "smallScale"
    label: "Small Scale Installations"
    description: "Add each artwork in the \"Small Scale Installations\" category."
    folder: "src/data/small-scale"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
          required: false
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "small-scale"
      }
  - name: "site-specific"
    label: "Site-Specific Installations"
    description: "Add each artwork in the \"Site-Specific Installations\" category."
    folder: "src/data/site-specific"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
          required: false
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "site-specific"
      }
  - name: "appliances"
    label: "Appliances (Objects)"
    description: "Add each artwork in the \"Appliances\" category."
    folder: "src/data/appliances"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
          required: false
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "appliances"
      }
  - name: "coping-mechanisms"
    label: "Coping Mechanisms (Objects)"
    description: "Add each artwork in the \"Coping Mechanisms\" category."
    folder: "src/data/coping-mechanisms"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
          required: false
      - label: "Video Links"
        name: "videoLinks"
        widget: "list"
        field:
          label: "Video Link"
          name: "videoLink"
          widget: "string"
          required: false
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - {
        label: "Category",
        name: "category",
        widget: "string",
        default: "coping mechanisms"
      }